### ISSUE TITLE
Error in DIF_test.m

### ISSUE THREAD

**Issue by mangost** [bewantbe/point-neuron-network-simulator#1]
In example_DIF_test.m
the following code 
```
f_exp_rise_fall = @(t, tg, th) tg*th*(exp(-t/tg) - exp(-t/th))/(tg-th) .* (t>0);
GE_ref = pm.ps * f_exp_rise_fall(s_t-5.0, pm.neuron_const(8), pm.neuron_const(9));
GI_ref =  pm.psi * f_exp_rise_fall(s_t-5.0, pm.neuron_const(10), pm.neuron_const(11));
G_ref = [GE_ref; GI_ref];
```

seems it shall be 
````
f_exp_rise_fall = @(t, tg, th) tg*th*(exp(-t/tg) - exp(-t/th))/(tg-th) .* (t>0);
GE_ref = abs(pm.input_event(1,3)) * f_exp_rise_fall(s_t-5.0, pm.neuron_const(8), pm.neuron_const(9));
GI_ref = abs(pm.input_event(2,3)) * f_exp_rise_fall(s_t-5.0, pm.neuron_const(10), pm.neuron_const(11));
G_ref = [GE_ref; GI_ref];
````

In your implementation, external input event is read in as poisson event with strength as given, there is no factor is ps or psi but the given strength.

----

Morever, MATLAB 2017a told me that no maxabs in-built. Maybe you need a max(max(abs()))

**Comment by bewantbe** [comment]
Nice catch! It should now fixed.

maxabs is defined as maxabs = @(x) max(abs(x(:)));
I've put it in the startup.m also. It is really handy when you need to compare two arrays that should be identical.
